repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    set:                                  
      - name: rbac.create
        value: false
  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    set:                                   
      - name: rbac.create
        value: false